'use client';

import { useEffect, useMemo, useState } from 'react';
import Link from 'next/link';
import { useRouter, useSearchParams } from 'next/navigation';
import Image from 'next/image';
import { Button } from '@/components/ui/button';
import { Card, CardContent, CardHeader, CardTitle } from '@/components/ui/card';
import { CheckCircle, Download, Home, Package } from 'lucide-react';
import html2pdf from 'html2pdf.js';
import SEOHead from '@/components/seo/SEOHead';
import { useHeadlessSEO } from '@/hooks/useYoastSEO';
import { getCanonicalUrl } from '@/lib/utils';
import { getSiteName, getContactEmail, getTenantConfig } from '@/lib/tenant-config';
import { generateOrganizationSchema, generateWebsiteSchema } from '@/lib/schema-generator';
import { WP_BASE_URL } from '@/lib/config';
import { useCartStore } from '@/store/cartStore';

const ORDER_CACHE_KEY = 'kitchenhero-latest-order';

const ensureDataLayer = () => {
  if (typeof window === 'undefined') return null;
  (window as any).dataLayer = (window as any).dataLayer || [];
  return (window as any).dataLayer as any[];
};

const pushDL = (event: string, payload: Record<string, unknown>) => {
  const dl = ensureDataLayer();
  if (!dl) return;
  dl.push({ event, ...payload });
};

type WooMeta = { id?: number; key?: string; value?: string | number | boolean };
type WooItem = {
  id: number | string;
  product_id?: number | string;
  name: string;
  quantity: number;
  total: string | number;
  subtotal?: string | number;
  price?: string | number;
  image?: { src?: string };
  meta_data?: WooMeta[];
};
type WooShippingLine = { total?: string | number; price?: string | number };
type WooOrder = {
  id: number | string;
  number?: string | number;
  date_created?: string;
  status?: string;
  payment_method_title?: string;
  payment_method?: string;
  currency?: string;
  total?: string | number;
  discount_total?: string | number;
  shipping_total?: string | number;
  line_items?: WooItem[];
  shipping_lines?: WooShippingLine[];
  billing?: {
    first_name?: string;
    last_name?: string;
    phone?: string;
    email?: string;
    address_1?: string;
    address_2?: string;
    city?: string;
    state?: string;
    postcode?: string;
    country?: string;
  };
  meta_data?: WooMeta[];
};

const num = (value?: string | number | null) => {
  const parsed = parseFloat((value ?? '0').toString());
  return Number.isFinite(parsed) ? parsed : 0;
};

const computeTotals = (order?: WooOrder | null) => {
  if (!order) {
    return { itemsSubtotal: 0, shippingAmount: 0, discountAmount: 0, grandTotal: 0 };
  }

  const itemsSubtotal = Array.isArray(order.line_items)
    ? order.line_items.reduce((sum, item) => sum + num(item.subtotal ?? item.total), 0)
    : 0;

  const shippingAmount =
    Array.isArray(order.shipping_lines) && order.shipping_lines.length > 0
      ? order.shipping_lines.reduce((sum, line) => sum + num(line.total ?? line.price), 0)
      : num(order.shipping_total);

  const discountAmount = Math.abs(num(order.discount_total));
  const totalValue = num(order.total);
  const grandTotal =
    totalValue > 0 ? totalValue : Math.max(0, itemsSubtotal - discountAmount + shippingAmount);

  return { itemsSubtotal, shippingAmount, discountAmount, grandTotal };
};

const hasVariationAttributes = (item: WooItem) =>
  Array.isArray(item.meta_data) &&
  item.meta_data.some((meta) => meta?.key?.startsWith?.('pa_') && meta.value);

const extractStateName = (order?: WooOrder | null) => {
  const stateMeta = order?.meta_data?.find((meta) => meta.key === '_kh_state_label');
  return (stateMeta?.value as string) || order?.billing?.state || '';
};

const isAutoGeneratedEmail = (email?: string) => {
  if (!email) return false;
  const tenantConfig = getTenantConfig();
  const autoDomain = tenantConfig.supportEmail.split('@')[1] || 'kitchenhero.xyz';
  return email.endsWith(`@${autoDomain}`);
};

const OrderConfirmationClient = () => {
  const router = useRouter();
  const searchParams = useSearchParams();
  const [order, setOrder] = useState<WooOrder | null>(null);
  const [hydrated, setHydrated] = useState(false);
  const { purchaseTracked, setPurchaseTracked } = useCartStore();
  const { seoData } = useHeadlessSEO('/order-confirmation');
  const siteName = getSiteName();
  const structuredData = useMemo(
    () => [
      generateWebsiteSchema(),
      generateOrganizationSchema(),
      ...(seoData?.json_ld ?? []),
    ],
    [seoData]
  );

  useEffect(() => {
    setHydrated(true);
    const cached = typeof window !== 'undefined' ? sessionStorage.getItem(ORDER_CACHE_KEY) : null;
    if (cached) {
      try {
        setOrder(JSON.parse(cached));
      } catch (error) {
        console.warn('Unable to parse cached order', error);
        sessionStorage.removeItem(ORDER_CACHE_KEY);
      }
      return;
    }

    const orderNumber = searchParams.get('order_number');
    if (!orderNumber) {
      router.push('/');
    }
  }, [router, searchParams]);

  useEffect(() => {
    return () => {
      setPurchaseTracked(false);
    };
  }, [setPurchaseTracked]);

  const { itemsSubtotal, shippingAmount, discountAmount, grandTotal } = useMemo(
    () => computeTotals(order),
    [order]
  );

  const currencyCode = order?.currency || '';
  const currencySymbol = useMemo(() => {
    const symbolMeta = order?.meta_data?.find((meta) => meta.key === '_kh_currency_symbol');
    if (typeof symbolMeta?.value === 'string' && symbolMeta.value.trim()) {
      return symbolMeta.value;
    }
    return currencyCode ? `${currencyCode} ` : '';
  }, [currencyCode, order]);

  useEffect(() => {
    if (!order || purchaseTracked) return;
    const customerName = [order.billing?.first_name, order.billing?.last_name]
      .filter(Boolean)
      .join(' ')
      .trim();

    pushDL('purchase', {
      event_category: 'ecommerce',
      event_label: 'order_confirmed',
      transaction_id: order.id?.toString() || order.number?.toString(),
      value: grandTotal,
      currency: currencyCode || undefined,
      customer_name: customerName,
      customer_phone: order.billing?.phone || '',
      customer_email: order.billing?.email || '',
      customer_address: order.billing?.address_1 || '',
      customer_state: extractStateName(order),
      payment_type: order.payment_method_title || 'Cash on delivery',
      items: (order.line_items || []).map((item) => ({
        item_id: item.product_id?.toString() || item.id?.toString(),
        item_name: item.name,
        price: num(item.price || item.total),
        quantity: item.quantity,
        item_category: 'product',
      })),
    });

    setPurchaseTracked(true);
  }, [order, purchaseTracked, grandTotal, currencyCode, setPurchaseTracked]);

  const generateReceiptPdf = async () => {
    if (!order) return;
    pushDL('download_receipt', {
      event_category: 'order_confirmation',
      event_label: 'receipt_download',
      order_number: order.number,
      order_value: grandTotal,
      currency: currencyCode || undefined,
    });

    const tenantConfig = getTenantConfig();
    const logoSrc = `${WP_BASE_URL}/wp-content/uploads/2025/08/Kitchenhero-logo.png`;
    const finalTotals = computeTotals(order);
    const receiptsElement = document.createElement('div');
    receiptsElement.style.width = '210mm';
    receiptsElement.style.padding = '20mm';
    receiptsElement.style.backgroundColor = '#ffffff';
    receiptsElement.style.fontFamily = "'Archivo', 'Helvetica', 'Arial', sans-serif";
    receiptsElement.style.fontSize = '14px';

    const billingName = [order.billing?.first_name, order.billing?.last_name].filter(Boolean).join(' ').trim();

    receiptsElement.innerHTML = `
      <style>
        @import url('https://fonts.googleapis.com/css2?family=Archivo:ital,wght@0,100..900;1,100..900&display=swap');
        * { font-family: 'Archivo', 'Helvetica', 'Arial', sans-serif !important; }
      </style>
      <div style="display:flex;justify-content:space-between;align-items:flex-start;margin-bottom:30px;border-bottom:2px solid #e0e0e0;padding-bottom:20px;">
        <div style="display:flex;align-items:center;gap:15px;">
          <img src="${logoSrc}" alt="${siteName} Logo" style="width:80px;height:auto;" />
          <div>
            <h1 style="font-size:32px;font-weight:700;margin:0;color:#000;">${siteName}</h1>
            <p style="margin:5px 0 0 0;color:#333;font-size:13px;">স্মার্ট কিচেনের স্মার্ট সমাধান</p>
          </div>
        </div>
        <div style="text-align:right;">
          <h2 style="font-size:22px;font-weight:700;margin:0;color:#000;">Order Receipt</h2>
          <div style="margin-top:8px;">
            <div style="font-weight:600;color:#000;font-size:15px;">Order #: ${order.number}</div>
            <div style="color:#333;margin-top:2px;font-size:14px;">Date: ${order.date_created ? new Date(order.date_created).toLocaleDateString() : ''}</div>
            <div style="color:#333;margin-top:2px;font-size:14px;">Status: <span style="color:#059669;font-weight:600;">${order.status || ''}</span></div>
          </div>
        </div>
      </div>
      <div style="display:flex;gap:40px;margin-bottom:30px;">
        <div style="flex:1;">
          <h2 style="font-size:18px;font-weight:700;margin-bottom:15px;color:#000;border-bottom:1px solid #ccc;padding-bottom:5px;">From:</h2>
          <div style="line-height:1.5;">
            <div style="font-weight:600;color:#000;font-size:15px;">${siteName}</div>
            <div style="color:#333;font-size:14px;">Phone: ${tenantConfig.phone}</div>
            <div style="color:#333;font-size:14px;">Email: ${getContactEmail()}</div>
          </div>
        </div>
        <div style="flex:1;">
          <h2 style="font-size:18px;font-weight:700;margin-bottom:15px;color:#000;border-bottom:1px solid #ccc;padding-bottom:5px;">Bill To:</h2>
          <div style="line-height:1.5;">
            <div style="color:#333;margin-bottom:2px;font-size:14px;"><strong>Name:</strong> ${billingName}</div>
            <div style="color:#333;margin-bottom:2px;font-size:14px;"><strong>Address:</strong> ${order.billing?.address_1 || ''}</div>
            ${order.billing?.address_2 ? `<div style="color:#333;margin-bottom:2px;font-size:14px;"><strong>Address 2:</strong> ${order.billing.address_2}</div>` : ''}
            <div style="color:#333;margin-bottom:2px;font-size:14px;"><strong>City/State:</strong> ${order.billing?.city || ''}, ${extractStateName(order)} ${order.billing?.postcode || ''}</div>
            <div style="color:#333;margin-bottom:2px;font-size:14px;"><strong>Country:</strong> ${order.billing?.country || 'BD'}</div>
            <div style="color:#333;margin-top:5px;font-size:14px;">
              <strong>Phone:</strong> ${order.billing?.phone || ''}
              ${!isAutoGeneratedEmail(order.billing?.email) ? `<br><strong>Email:</strong> ${order.billing?.email || ''}` : ''}
            </div>
          </div>
        </div>
      </div>
      <table style="width:100%;border-collapse:collapse;margin-bottom:25px;border:1px solid #ccc;border-radius:8px;overflow:hidden;font-family:'Archivo',sans-serif;">
        <thead style="background:#f5f5f5;border-bottom:1px solid #ccc;">
          <tr>
            <th style="text-align:left;padding:14px 16px;font-weight:600;color:#000;border-right:1px solid #ccc;font-size:15px;">Item</th>
            <th style="text-align:center;padding:14px 16px;font-weight:600;color:#000;border-right:1px solid #ccc;font-size:15px;">Qty</th>
            <th style="text-align:center;padding:14px 16px;font-weight:600;color:#000;border-right:1px solid #ccc;font-size:15px;">Price</th>
            <th style="text-align:right;padding:14px 16px;font-weight:600;color:#000;font-size:15px;">Total</th>
          </tr>
        </thead>
        <tbody>
          ${(order.line_items || [])
            .map((item, index) => {
              const variations =
                item.meta_data
                  ?.filter((meta) => meta?.key?.startsWith?.('pa_') && meta.value)
                  .map(
                    (meta) =>
                      `${meta.key?.replace('pa_', '')?.replace(/_/g, ' ')}: ${meta.value}`
                  )
                  .join(', ') || '';
              return `
                <tr style="border-bottom:1px solid #e0e0e0;${index % 2 === 0 ? 'background:#fafafa;' : ''}">
                  <td style="padding:14px 16px;border-right:1px solid #ccc;font-family:'Archivo',sans-serif;">
                    <div style="font-weight:500;color:#000;font-size:14px;">${item.name}</div>
                    ${variations ? `<div style="font-size:12px;color:#333;margin-top:3px;">${variations}</div>` : ''}
                  </td>
                  <td style="text-align:center;padding:14px 16px;border-right:1px solid #ccc;color:#000;font-size:14px;">${item.quantity}</td>
                  <td style="text-align:center;padding:14px 16px;border-right:1px solid #ccc;color:#000;font-size:14px;">${currencySymbol}${num(item.price ?? item.total).toFixed(2)}</td>
                  <td style="text-align:right;padding:14px 16px;font-weight:500;color:#000;font-size:14px;">${currencySymbol}${num(item.total).toFixed(2)}</td>
                </tr>
              `;
            })
            .join('')}
        </tbody>
      </table>
      <div style="display:flex;justify-content:flex-end;margin-bottom:30px;">
        <div style="width:320px;background:#f9f9f9;border:1px solid #ccc;border-radius:8px;padding:24px;">
          <div style="display:flex;justify-content:space-between;padding:10px 0;border-bottom:1px solid #ccc;">
            <span style="color:#333;font-size:15px;">Subtotal</span>
            <span style="color:#000;font-weight:500;font-size:15px;">${currencySymbol}${finalTotals.itemsSubtotal.toFixed(2)}</span>
          </div>
          ${
            finalTotals.shippingAmount > 0
              ? `<div style="display:flex;justify-content:space-between;padding:10px 0;border-bottom:1px solid #ccc;">
                  <span style="color:#333;font-size:15px;">Shipping</span>
                  <span style="color:#000;font-weight:500;font-size:15px;">${currencySymbol}${finalTotals.shippingAmount.toFixed(2)}</span>
                </div>`
              : `<div style="display:flex;justify-content:space-between;padding:10px 0;border-bottom:1px solid #ccc;">
                  <span style="color:#333;font-size:15px;">Shipping</span>
                  <span style="color:#000;font-weight:500;font-size:15px;">Free Delivery</span>
                </div>`
          }
          ${
            finalTotals.discountAmount > 0
              ? `<div style="display:flex;justify-content:space-between;padding:10px 0;border-bottom:1px solid #ccc;">
                  <span style="color:#333;font-size:15px;">Discount</span>
                  <span style="color:#dc2626;font-weight:500;font-size:15px;">-${currencySymbol}${finalTotals.discountAmount.toFixed(2)}</span>
                </div>`
              : ''
          }
          <div style="display:flex;justify-content:space-between;padding:14px 0;margin-top:10px;border-top:2px solid #000;font-weight:700;font-size:18px;">
            <span style="color:#000;">Total</span>
            <span style="color:#000;">${currencySymbol}${finalTotals.grandTotal.toFixed(2)}</span>
          </div>
        </div>
      </div>
      <div style="text-align:center;margin-top:40px;padding-top:20px;border-top:1px solid #ccc;">
        <div style="font-size:16px;font-weight:600;color:#000;margin-bottom:8px;">Thank You for Your Order!</div>
        <div style="font-size:13px;color:#333;">For any questions, please contact us at ${getContactEmail()} or call ${tenantConfig.phone}</div>
      </div>
    `;

    document.body.appendChild(receiptsElement);
    try {
      await html2pdf()
        .set({
          margin: 0,
          filename: `receipt_${order.number}.pdf`,
          image: { type: 'jpeg', quality: 0.98 },
          html2canvas: { scale: 2, useCORS: true },
          jsPDF: { unit: 'mm', format: 'a4', orientation: 'portrait' },
        })
        .from(receiptsElement)
        .save();
    } catch (error) {
      console.error('PDF generation failed', error);
    } finally {
      receiptsElement.remove();
    }
  };

  if (!hydrated) {
    return null;
  }

  if (!order) {
    return (
      <div className="container mx-auto px-4 py-12 text-center space-y-4">
        <p className="text-sm text-muted-foreground uppercase tracking-[0.3em]">Order Confirmation</p>
        <h1 className="text-3xl font-bold">Order not found</h1>
        <p className="text-muted-foreground">We could not find your order. It may have expired or been cleared from your session.</p>
        <div className="flex flex-col gap-3 sm:flex-row sm:justify-center">
          <Button asChild>
            <Link href="/">Go to homepage</Link>
          </Button>
          <Button variant="ghost" asChild>
            <Link href="/products">Browse products</Link>
          </Button>
        </div>
      </div>
    );
  }

  return (
    <>
      <SEOHead
        seoData={seoData}
        fallback={{
          title: `Order Confirmation - ${siteName}`,
          description: `Thank you for your purchase! Your order is confirmed with ${siteName}.`,
          canonical: getCanonicalUrl('/order-confirmation'),
        }}
        structuredData={structuredData}
      />
      <div className="container mx-auto px-4 py-10 text-left space-y-8">
        <div className="text-center space-y-3">
          <p className="text-xs uppercase tracking-[0.5em] text-muted-foreground">Order Confirmation</p>
          <CheckCircle className="mx-auto h-16 w-16 text-emerald-500" />
          <h1 className="text-3xl font-bold">Order Confirmed!</h1>
          <p className="text-muted-foreground">
            Thank you for your purchase. We are processing your order and will message you with updates.
          </p>
        </div>

        <Card>
          <CardHeader>
            <CardTitle className="flex items-center justify-center gap-2">
              <Package className="h-5 w-5 text-primary" />
              Order details
            </CardTitle>
          </CardHeader>
          <CardContent className="space-y-6">
            <div className="grid grid-cols-2 gap-4 text-sm">
              <div>
                <p className="font-semibold">Order Number:</p>
                <p className="text-muted-foreground">{order.number}</p>
              </div>
              <div className="text-right">
                <p className="font-semibold">Total:</p>
                <p className="text-muted-foreground font-semibold">{currencySymbol}{grandTotal.toFixed(2)}</p>
              </div>
              <div>
                <p className="font-semibold">Order Date:</p>
                <p className="text-muted-foreground">{order.date_created ? new Date(order.date_created).toLocaleDateString() : ''}</p>
              </div>
              <div className="text-right">
                <p className="font-semibold">Status:</p>
                <p className="text-emerald-600 font-semibold capitalize">{order.status || 'Processing'}</p>
              </div>
            </div>

            <div className="rounded-lg border border-border bg-muted/50 p-4">
              <h3 className="font-semibold text-base mb-2">Customer information</h3>
              <div className="grid grid-cols-1 md:grid-cols-2 gap-3 text-sm">
                <div>
                  <p className="font-medium">Name</p>
                  <p className="text-muted-foreground">{[order.billing?.first_name, order.billing?.last_name].filter(Boolean).join(' ')}</p>
                </div>
                <div>
                  <p className="font-medium">Phone</p>
                  <p className="text-muted-foreground">{order.billing?.phone || '—'}</p>
                </div>
                {!isAutoGeneratedEmail(order.billing?.email) && (
                  <div>
                    <p className="font-medium">Email</p>
                    <p className="text-muted-foreground">{order.billing?.email || '—'}</p>
                  </div>
                )}
                <div>
                  <p className="font-medium">Address</p>
                  <p className="text-muted-foreground">{order.billing?.address_1 || '—'}</p>
                </div>
                <div className="md:col-span-2">
                  <p className="font-medium">State / Division</p>
                  <p className="text-muted-foreground">{extractStateName(order)}</p>
                </div>
              </div>
            </div>

            <div className="space-y-3 text-sm">
              <div className="flex justify-between">
                <span>Subtotal</span>
                <span>{currencySymbol}{itemsSubtotal.toFixed(2)}</span>
              </div>
              <div className="flex justify-between">
                <span>Shipping</span>
                <span>
                  {shippingAmount === 0 ? 'Free delivery' : `${currencySymbol}${shippingAmount.toFixed(2)}`}
                </span>
              </div>
              {discountAmount > 0 && (
                <div className="flex justify-between text-sm text-red-600">
                  <span>Discount</span>
                  <span>-{currencySymbol}{discountAmount.toFixed(2)}</span>
                </div>
              )}
              <div className="flex justify-between border-t pt-2 font-semibold text-base">
                <span>Total</span>
                <span>{currencySymbol}{grandTotal.toFixed(2)}</span>
              </div>
              <div className="text-sm text-muted-foreground">
                Payment: {order.payment_method_title || 'Cash on delivery'}
              </div>
            </div>
          </CardContent>
        </Card>

        <div className="space-y-4">
          <h3 className="text-lg font-semibold">Items</h3>
          <ul className="space-y-3">
            {(order.line_items || []).map((item) => (
              <li key={item.id} className="rounded-lg border border-border p-4 flex gap-4 items-start">
                {item.image?.src ? (
                  <Image
                    src={item.image.src}
                    alt={item.name}
                    width={64}
                    height={64}
                    className="w-16 h-16 object-cover rounded-md"
                    unoptimized
                  />
                ) : (
                  <div className="w-16 h-16 bg-muted rounded-md flex items-center justify-center">
                    <Package className="w-7 h-7 text-muted-foreground" />
                  </div>
                )}
                <div className="flex-1">
                  <div className="font-medium">{item.name}</div>
                  {hasVariationAttributes(item) && (
                    <div className="text-xs text-muted-foreground mt-1 space-y-1">
                      {item.meta_data
                        ?.filter((meta) => meta?.key?.startsWith?.('pa_') && meta.value)
                        .map((meta) => (
                          <div key={`${meta.key}-${meta.value}`} className="capitalize">
                            <span className="font-semibold">{meta.key?.replace('pa_', '')?.replace(/_/g, ' ')}:</span> {meta.value}
                          </div>
                        ))}
                    </div>
                  )}
                  <div className="text-muted-foreground text-xs mt-1">Qty: {item.quantity}</div>
                </div>
                <div className="font-semibold text-sm">
                  {currencySymbol}{num(item.total).toFixed(2)}
                </div>
              </li>
            ))}
          </ul>
        </div>

        <div className="flex flex-col gap-3 sm:flex-row">
          <Button onClick={generateReceiptPdf} className="flex-1" variant="outline">
            <Download className="w-4 h-4 mr-2" />
            Download receipt
          </Button>
          <Button asChild className="flex-1">
            <Link href="/products">
              <Home className="w-4 h-4 mr-2" />
              Continue shopping
            </Link>
          </Button>
        </div>
      </div>
    </>
  );
};

export default OrderConfirmationClient;
