// src/pages/OrderConfirmation.tsx
import React, { useEffect } from "react";
import { useLocation, useNavigate } from "react-router-dom";
import { useCartStore } from "@/store/cartStore";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { CheckCircle, Package, Home, Download } from "lucide-react";
import html2pdf from "html2pdf.js";
import SEOHead from "@/components/seo/SEOHead";
import { useHeadlessSEO } from "@/hooks/useYoastSEO";
import { getCanonicalUrl } from "@/lib/utils";
import { getSiteName, getContactEmail, getTenantConfig } from "@/lib/tenant-config";
import { WP_BASE_URL } from "@/lib/config";

/** ---------------------------
 *  GA4 helpers
 *  --------------------------*/
const ensureDataLayer = () => {
  if (typeof window === "undefined") return null;
  (window as Window & { dataLayer?: unknown[] }).dataLayer = (window as Window & { dataLayer?: unknown[] }).dataLayer || [];
  return (window as Window & { dataLayer?: unknown[] }).dataLayer as unknown[];
};

const pushDL = (event: string, payload: Record<string, unknown>) => {
  const dl = ensureDataLayer();
  if (!dl) return;
  dl.push({ event, ...payload });
  // GA4 events are pushed to dataLayer (no console logging)
};

/** ---------------------------
 *  Types (matches Woo order shape)
 *  --------------------------*/
type WooMeta = { id?: number; key?: string; value?: string | number | boolean };
type WooItem = {
  id: number | string;
  product_id?: number | string;
  name: string;
  quantity: number;
  total: string | number;
  subtotal?: string | number;
  price?: string | number;
  image?: { src?: string };
  meta_data?: WooMeta[];
};
type WooShippingLine = { total?: string | number; price?: string | number };
type WooOrder = {
  id: number | string;
  number?: string | number;
  date_created?: string;
  status?: string;
  payment_method_title?: string;
  payment_method?: string;
  currency?: string;
  total?: string | number;
  discount_total?: string | number;
  shipping_total?: string | number;
  line_items?: WooItem[];
  shipping_lines?: WooShippingLine[];
  billing?: {
    first_name?: string;
    last_name?: string;
    phone?: string;
    email?: string;
    address_1?: string;
    address_2?: string;
    city?: string;
    state?: string;
    postcode?: string;
    country?: string;
  };
  meta_data?: WooMeta[];
};

/** ---------------------------
 *  Utilities
 *  --------------------------*/
const num = (v: string | number | undefined | null) => {
  const n = parseFloat((v ?? "0").toString());
  return Number.isFinite(n) ? n : 0;
};

const computeTotals = (ord?: WooOrder | null) => {
  if (!ord)
    return {
      itemsSubtotal: 0,
      shippingAmount: 0,
      discountAmount: 0,
      grandTotal: 0,
    };

  const itemsSubtotal = Array.isArray(ord.line_items)
    ? ord.line_items.reduce(
        (s: number, it: WooItem) => s + num(it.subtotal ?? it.total),
        0
      )
    : 0;

  const shippingAmount =
    Array.isArray(ord.shipping_lines) && ord.shipping_lines.length > 0
      ? ord.shipping_lines.reduce(
          (s: number, sl: WooShippingLine) => s + num(sl.total ?? sl.price),
          0
        )
      : num(ord.shipping_total);

  const discountAmount = Math.abs(num(ord.discount_total));
  const parsedTotal = num(ord.total);

  const grandTotal =
    parsedTotal > 0
      ? parsedTotal
      : Math.max(0, itemsSubtotal - discountAmount + shippingAmount);

  return { itemsSubtotal, shippingAmount, discountAmount, grandTotal };
};

const hasVariationAttributes = (item: WooItem) =>
  Array.isArray(item.meta_data) &&
  item.meta_data.some((meta) => meta?.key?.startsWith?.("pa_") && meta.value);

const isAutoGeneratedEmail = (email?: string) => {
  if (!email) return false;
  const tenantConfig = getTenantConfig();
  const emailDomain = tenantConfig.supportEmail.split('@')[1] || 'kitchenhero.xyz';
  return email.endsWith(`@${emailDomain}`);
};

const getStateName = (order?: WooOrder | null) => {
  if (!order) return "";
  const stateMeta = order.meta_data?.find((m) => m.key === "_kh_state_label");
  return (stateMeta?.value as string) || order.billing?.state || "";
};

/** ---------------------------
 *  Component
 *  --------------------------*/
const OrderConfirmation: React.FC = () => {
  const location = useLocation();
  const navigate = useNavigate();
  const { order } = (location.state || {}) as { order?: WooOrder | null };
  const { purchaseTracked, setPurchaseTracked } = useCartStore();

  // Clear purchase tracking when leaving order confirmation page
  useEffect(() => {
    return () => {
      setPurchaseTracked(false);
    };
  }, [setPurchaseTracked]);

  const { itemsSubtotal, shippingAmount, discountAmount, grandTotal } =
    computeTotals(order);

  const currencyCode = order?.currency || "";
  const currencySymbol = (() => {
    const metaSymbol = order?.meta_data?.find((m) => m.key === "_kh_currency_symbol")
      ?.value;
    if (typeof metaSymbol === "string" && metaSymbol.trim()) {
      return metaSymbol;
    }
    return currencyCode ? `${currencyCode} ` : "";
  })();

  // Track purchase event with user input data
  useEffect(() => {
    if (order && !purchaseTracked) {
      const customerName = [
        order.billing?.first_name || "",
        order.billing?.last_name || "",
      ].join(" ").trim();

      pushDL("purchase", {
        event_category: "ecommerce",
        event_label: "order_completed",
        transaction_id: order.id?.toString() || order.number?.toString(),
        value: grandTotal,
        currency: currencyCode || undefined,
        // Include user input data for tracking
        customer_name: customerName,
        customer_phone: order.billing?.phone || "",
        customer_email: order.billing?.email || "",
        customer_address: order.billing?.address_1 || "",
        customer_state: getStateName(order),
        payment_type: order.payment_method_title || "Cash on delivery",
        items: (order.line_items || []).map((item) => ({
          item_id: item.product_id?.toString() || item.id?.toString(),
          item_name: item.name,
          price: num(item.price),
          quantity: item.quantity,
          item_category: "product",
        })),
      });

      setPurchaseTracked(true);
    }
  }, [order, purchaseTracked, grandTotal, setPurchaseTracked]);

  if (!order) return null;

  /** PDF generation */
  const generateReceiptPdf = async () => {
      pushDL("download_receipt", {
        event_category: "order_confirmation",
        event_label: "receipt_download",
        order_number: order.number,
        order_value: grandTotal,
        currency: currencyCode || undefined,
      });

    const {
      itemsSubtotal: pdfItemsSubtotal,
      shippingAmount: pdfShippingAmount,
      discountAmount: pdfDiscountAmount,
      grandTotal: finalTotal,
    } = computeTotals(order);

    const baseUrl = WP_BASE_URL;
    const tenantConfig = getTenantConfig();
    const siteName = getSiteName();
    const contactEmail = getContactEmail();

    const receiptElement = document.createElement("div");
    receiptElement.style.width = "210mm";
    receiptElement.style.padding = "20mm";
    receiptElement.style.fontFamily = "'Archivo', 'Helvetica', 'Arial', sans-serif";
    receiptElement.style.fontSize = "14px";
    receiptElement.style.backgroundColor = "#ffffff";

    const logoSrc = `${baseUrl}/wp-content/uploads/2025/08/Kitchenhero-logo.png`;

    receiptElement.innerHTML = `
      <style>
        @import url('https://fonts.googleapis.com/css2?family=Archivo:ital,wght@0,100..900;1,100..900&display=swap');
        * { font-family: 'Archivo', 'Helvetica', 'Arial', sans-serif !important; }
      </style>
      <div style="display:flex;justify-content:space-between;align-items:flex-start;margin-bottom:30px;border-bottom:2px solid #e0e0e0;padding-bottom:20px;">
        <div style="display:flex;align-items:center;gap:15px;">
          <img src="${logoSrc}" alt="${siteName} Logo" style="width:80px;height:auto;" />
          <div>
            <h1 style="font-size:32px;font-weight:700;margin:0;color:#000000;font-family:'Archivo',sans-serif;">${siteName}</h1>
            <p style="margin:5px 0 0 0;color:#333333;font-size:13px;font-family:'Archivo',sans-serif;">স্মার্ট কিচেনের স্মার্ট সমাধান</p>
          </div>
        </div>
        <div style="text-align:right;">
          <h2 style="font-size:22px;font-weight:700;margin:0;color:#000000;font-family:'Archivo',sans-serif;">Order Receipt</h2>
          <div style="margin-top:8px;">
            <div style="font-weight:600;color:#000000;font-size:15px;font-family:'Archivo',sans-serif;">Order #: ${order.number}</div>
            <div style="color:#333333;margin-top:2px;font-size:14px;font-family:'Archivo',sans-serif;">Date: ${order.date_created ? new Date(order.date_created).toLocaleDateString() : ""}</div>
            <div style="color:#333333;margin-top:2px;font-size:14px;font-family:'Archivo',sans-serif;">Status: <span style="color:#059669;font-weight:600;">${order.status ?? ""}</span></div>
          </div>
        </div>
      </div>

      <div style="display:flex;gap:40px;margin-bottom:30px;">
        <div style="flex:1;">
          <h2 style="font-size:18px;font-weight:700;margin-bottom:15px;color:#000000;border-bottom:1px solid #cccccc;padding-bottom:5px;font-family:'Archivo',sans-serif;">From:</h2>
          <div style="line-height:1.5;">
            <div style="font-weight:600;color:#000000;font-size:15px;font-family:'Archivo',sans-serif;">${siteName}</div>
            <div style="color:#333333;font-size:14px;font-family:'Archivo',sans-serif;">Phone: ${tenantConfig.phone}</div>
            <div style="color:#333333;font-size:14px;font-family:'Archivo',sans-serif;">Email: ${contactEmail}</div>
          </div>
        </div>

        <div style="flex:1;">
          <h2 style="font-size:18px;font-weight:700;margin-bottom:15px;color:#000000;border-bottom:1px solid #cccccc;padding-bottom:5px;font-family:'Archivo',sans-serif;">Bill To:</h2>
          <div style="line-height:1.5;">
            <div style="color:#333333;margin-bottom:2px;font-size:14px;font-family:'Archivo',sans-serif;"><strong style="color:#000000;font-family:'Archivo',sans-serif;">Name:</strong> ${[
              order.billing?.first_name || "",
              order.billing?.last_name || "",
            ]
              .join(" ")
              .trim()}</div>
            <div style="color:#333333;margin-bottom:2px;font-size:14px;font-family:'Archivo',sans-serif;"><strong style="color:#000000;font-family:'Archivo',sans-serif;">Address:</strong> ${order.billing?.address_1 || ""}</div>
            ${order.billing?.address_2 ? `<div style="color:#333333;margin-bottom:2px;font-size:14px;font-family:'Archivo',sans-serif;"><strong style="color:#000000;font-family:'Archivo',sans-serif;">Address 2:</strong> ${order.billing.address_2}</div>` : ""}
            <div style="color:#333333;margin-bottom:2px;font-size:14px;font-family:'Archivo',sans-serif;"><strong style="color:#000000;font-family:'Archivo',sans-serif;">City/State:</strong> ${order.billing?.city || ""}, ${getStateName(order)} ${order.billing?.postcode || ""}</div>
            <div style="color:#333333;margin-bottom:2px;font-size:14px;font-family:'Archivo',sans-serif;"><strong style="color:#000000;font-family:'Archivo',sans-serif;">Country:</strong> ${order.billing?.country || "BD"}</div>
            <div style="color:#333333;margin-top:5px;font-size:14px;font-family:'Archivo',sans-serif;">
              <strong style="color:#000000;font-family:'Archivo',sans-serif;">Phone:</strong> ${order.billing?.phone || ""}
              ${!isAutoGeneratedEmail(order.billing?.email) ? `<br><strong style="color:#000000;font-family:'Archivo',sans-serif;">Email:</strong> ${order.billing?.email || ""}` : ""}
            </div>
          </div>
        </div>
      </div>

      <table style="width:100%;border-collapse:collapse;margin-bottom:25px;border:1px solid #cccccc;border-radius:8px;overflow:hidden;font-family:'Archivo',sans-serif;">
        <thead style="background:#f5f5f5;border-bottom:1px solid #cccccc;">
          <tr>
            <th style="text-align:left;padding:14px 16px;font-weight:600;color:#000000;border-right:1px solid #cccccc;font-size:15px;font-family:'Archivo',sans-serif;">Item</th>
            <th style="text-align:center;padding:14px 16px;font-weight:600;color:#000000;border-right:1px solid #cccccc;font-size:15px;font-family:'Archivo',sans-serif;">Qty</th>
            <th style="text-align:center;padding:14px 16px;font-weight:600;color:#000000;border-right:1px solid #cccccc;font-size:15px;font-family:'Archivo',sans-serif;">Price</th>
            <th style="text-align:right;padding:14px 16px;font-weight:600;color:#000000;font-size:15px;font-family:'Archivo',sans-serif;">Total</th>
          </tr>
        </thead>
        <tbody>
          ${
            (order.line_items || [])
              .map((item, index) => {
                const variations =
                  item.meta_data
                    ?.filter((m) => m?.key?.startsWith?.("pa_") && m.value)
                    .map(
                      (m) =>
                        `${m.key?.replace("pa_", "")?.replace(/_/g, " ")}: ${m.value}`
                    )
                    .join(", ") || "";
                return `
            <tr style="border-bottom:1px solid #e0e0e0;${index % 2 === 0 ? "background:#fafafa;" : ""}">
              <td style="padding:14px 16px;border-right:1px solid #cccccc;font-family:'Archivo',sans-serif;">
                <div style="font-weight:500;color:#000000;font-size:14px;font-family:'Archivo',sans-serif;">${item.name}</div>
                ${
                  variations
                    ? `<div style="font-size:12px;color:#333333;margin-top:3px;font-family:'Archivo',sans-serif;">${variations}</div>`
                    : ""
                }
              </td>
              <td style="text-align:center;padding:14px 16px;border-right:1px solid #cccccc;color:#000000;font-size:14px;font-family:'Archivo',sans-serif;">${
                item.quantity
              }</td>
              <td style="text-align:center;padding:14px 16px;border-right:1px solid #cccccc;color:#000000;font-size:14px;font-family:'Archivo',sans-serif;">${currencySymbol}${num(
                item.price ?? item.total
              ).toFixed(2)}</td>
              <td style="text-align:right;padding:14px 16px;font-weight:500;color:#000000;font-size:14px;font-family:'Archivo',sans-serif;">${currencySymbol}${num(
                item.total
              ).toFixed(2)}</td>
            </tr>`;
              })
              .join("")
          }
        </tbody>
      </table>

      <div style="display:flex;justify-content:flex-end;margin-bottom:30px;">
        <div style="width:320px;background:#f9f9f9;border:1px solid #cccccc;border-radius:8px;padding:24px;font-family:'Archivo',sans-serif;">
          <div style="display:flex;justify-content:space-between;padding:10px 0;border-bottom:1px solid #cccccc;">
            <span style="color:#333333;font-size:15px;font-family:'Archivo',sans-serif;">Subtotal</span>
            <span style="color:#000000;font-weight:500;font-size:15px;font-family:'Archivo',sans-serif;">${currencySymbol}${pdfItemsSubtotal.toFixed(2)}</span>
          </div>
          ${
            pdfShippingAmount > 0
              ? `<div style="display:flex;justify-content:space-between;padding:10px 0;border-bottom:1px solid #cccccc;">
            <span style="color:#333333;font-size:15px;font-family:'Archivo',sans-serif;">Shipping</span>
            <span style="color:#000000;font-weight:500;font-size:15px;font-family:'Archivo',sans-serif;">${currencySymbol}${pdfShippingAmount.toFixed(2)}</span>
          </div>`
              : `<div style="display:flex;justify-content:space-between;padding:10px 0;border-bottom:1px solid #cccccc;">
            <span style="color:#333333;font-size:15px;font-family:'Archivo',sans-serif;">Shipping</span>
            <span style="color:#000000;font-weight:500;font-size:15px;font-family:'Archivo',sans-serif;">Free Delivery</span>
          </div>`
          }
          ${
            pdfDiscountAmount > 0
              ? `<div style="display:flex;justify-content:space-between;padding:10px 0;border-bottom:1px solid #cccccc;">
            <span style="color:#333333;font-size:15px;font-family:'Archivo',sans-serif;">Discount</span>
            <span style="color:#dc2626;font-weight:500;font-size:15px;font-family:'Archivo',sans-serif;">-${currencySymbol}${pdfDiscountAmount.toFixed(2)}</span>
          </div>`
              : ""
          }
          <div style="display:flex;justify-content:space-between;padding:14px 0;margin-top:10px;border-top:2px solid #000000;font-weight:700;font-size:18px;">
            <span style="color:#000000;font-family:'Archivo',sans-serif;">Total</span>
            <span style="color:#000000;font-family:'Archivo',sans-serif;">${currencySymbol}${finalTotal.toFixed(2)}</span>
          </div>
        </div>
      </div>

      <div style="text-align:center;margin-top:40px;padding-top:20px;border-top:1px solid #cccccc;">
        <div style="font-size:16px;font-weight:600;color:#000000;margin-bottom:8px;font-family:'Archivo',sans-serif;">Thank You for Your Order!</div>
        <div style="font-size:13px;color:#333333;font-family:'Archivo',sans-serif;">For any questions, please contact us at ${getContactEmail()} or call ${getTenantConfig().phone}</div>
      </div>
    `;

    document.body.appendChild(receiptElement);

    try {
      await html2pdf()
        .set({
          margin: 0,
          filename: `receipt_${order.number}.pdf`,
          image: { type: "jpeg", quality: 0.98 },
          html2canvas: { scale: 2, useCORS: true },
          jsPDF: { unit: "mm", format: "a4", orientation: "portrait" },
        })
        .from(receiptElement)
        .save();
    } catch (err) {
      // eslint-disable-next-line no-console
      console.error("PDF generation failed", err);
    } finally {
      receiptElement.remove();
    }
  };

  const { seoData } = useHeadlessSEO('/order-confirmation');
  const siteName = getSiteName();

  return (
    <>
      <SEOHead
        seoData={seoData}
        fallback={{
          title: `Order Confirmation - ${siteName}`,
          description: `Thank you for your purchase! Your order has been successfully placed with ${siteName}.`,
          canonical: getCanonicalUrl('/order-confirmation'),
        }}
      />

        <div className="container mx-auto px-4 py-8 text-left">
          <div className="max-w-2xl mx-auto text-center">
            <div className="mb-8">
              <CheckCircle className="h-16 w-16 text-green-500 mx-auto mb-4" />
              <h1 className="text-3xl font-bold mb-2">Order Confirmed!</h1>
              <p className="text-muted-foreground">
                Thank you for your purchase. Your order has been successfully placed.
              </p>
            </div>

            <Card className="mb-8 text-left">
              <CardHeader>
                <CardTitle className="flex items-center justify-center gap-2">
                  <Package className="h-5 w-5" />
                  Order Details
                </CardTitle>
              </CardHeader>

              <CardContent className="space-y-4">
                <div className="grid grid-cols-2 gap-4">
                  <div>
                    <p className="font-semibold">Order Number:</p>
                    <p className="text-muted-foreground">{order.number}</p>
                  </div>
                  <div className="text-right">
                    <p className="font-semibold">Total Amount:</p>
                    <p className="text-muted-foreground font-bold">{currencySymbol}{grandTotal.toFixed(2)}</p>
                  </div>
                  <div>
                    <p className="font-semibold">Order Date:</p>
                    <p className="text-muted-foreground">
                      {order.date_created
                        ? new Date(order.date_created).toLocaleDateString()
                        : ""}
                    </p>
                  </div>
                  <div className="text-right">
                    <p className="font-semibold">Status:</p>
                    <p className="text-green-600 font-semibold capitalize">
                      {order.status}
                    </p>
                  </div>
                </div>

                {/* Customer Information */}
                <div className="mt-6 p-4 bg-gray-50 rounded-lg">
                  <h3 className="font-semibold mb-3 text-lg">Customer Information</h3>
                  <div className="grid grid-cols-1 md:grid-cols-2 gap-4 text-sm">
                    <div>
                      <p className="font-medium">Name:</p>
                      <p className="text-muted-foreground">
                        {(order.billing?.first_name || "") +
                          " " +
                          (order.billing?.last_name || "")}
                      </p>
                    </div>
                    <div>
                      <p className="font-medium">Phone:</p>
                      <p className="text-muted-foreground">{order.billing?.phone || ""}</p>
                    </div>
                    {!isAutoGeneratedEmail(order.billing?.email) && (
                      <div>
                        <p className="font-medium">Email:</p>
                        <p className="text-muted-foreground">{order.billing?.email || ""}</p>
                      </div>
                    )}
                    <div>
                      <p className="font-medium">Address:</p>
                      <p className="text-muted-foreground">{order.billing?.address_1 || ""}</p>
                    </div>
                    <div className="md:col-span-2">
                      <p className="font-medium">State/Division:</p>
                      <p className="text-muted-foreground">{getStateName(order)}</p>
                    </div>
                  </div>
                </div>

                {/* Totals Breakdown */}
                <div className="mt-2 space-y-1 text-sm">
                  <div className="flex justify-between">
                    <span>Subtotal</span>
                    <span>{currencySymbol}{itemsSubtotal.toFixed(2)}</span>
                  </div>
                  {shippingAmount > 0 && (
                    <div className="flex justify-between">
                      <span>Shipping</span>
                      <span>{currencySymbol}{shippingAmount.toFixed(2)}</span>
                    </div>
                  )}
                  {shippingAmount === 0 && (
                    <div className="flex justify-between">
                      <span>Shipping</span>
                      <span>Free Delivery</span>
                    </div>
                  )}
                  {discountAmount > 0 && (
                    <div className="flex justify-between text-red-600">
                      <span>Discount</span>
                      <span>-{currencySymbol}{discountAmount.toFixed(2)}</span>
                    </div>
                  )}
                  <div className="flex justify-between font-semibold border-t pt-2 mt-1">
                    <span>Total</span>
                    <span>{currencySymbol}{grandTotal.toFixed(2)}</span>
                  </div>
                </div>

                {/* Items */}
                <div className="mt-6">
                  <p className="font-semibold mb-2">Ordered Items:</p>
                  <ul className="space-y-3">
                    {(order.line_items || []).map((item) => (
                      <li
                        key={item.id}
                        className="border rounded-lg p-3 flex gap-4 items-start"
                      >
                        {item.image?.src ? (
                          <img
                            src={item.image.src}
                            alt={item.name}
                            className="w-16 h-16 object-cover rounded-md flex-shrink-0"
                            loading="lazy"
                          />
                        ) : (
                          <div className="w-16 h-16 bg-gray-200 rounded-md flex items-center justify-center text-gray-400 flex-shrink-0">
                            <Package size={24} />
                          </div>
                        )}

                        <div className="flex-1">
                          <div className="font-medium leading-tight">{item.name}</div>
                          {hasVariationAttributes(item) && (
                            <div className="text-xs text-gray-600 mt-1">
                              {item.meta_data
                                ?.filter((m) => m?.key?.startsWith?.("pa_") && m.value)
                                .map((m) => (
                                  <div key={`${m.key}-${m.value}`}>
                                    <span className="font-semibold capitalize">
                                      {m.key?.replace("pa_", "")?.replace(/_/g, " ")}:
                                    </span>{" "}
                                    {m.value as string}
                                  </div>
                                ))}
                            </div>
                          )}
                          <div className="text-sm text-muted-foreground mt-1">
                            Qty: {item.quantity}
                          </div>
                        </div>

                        <div className="font-semibold text-sm">
                          {currencySymbol}{num(item.total).toFixed(2)}
                        </div>
                      </li>
                    ))}
                  </ul>
                </div>
              </CardContent>
            </Card>

            <div className="flex justify-center gap-4">
              <Button onClick={generateReceiptPdf} className="flex-1" size="lg" variant="outline">
                <Download className="w-5 h-5 mr-2" /> Download Receipt
              </Button>

              <Button asChild className="flex-1" size="lg" variant="default">
                <a href="/">
                  <Home className="w-5 h-5 mr-2" /> Back to Home
                </a>
              </Button>
            </div>
          </div>
        </div>
      </>
  );
};

export default OrderConfirmation;

